# Rubocop configuration file
# resources:
# https://github.com/rubocop-hq/rubocop/blob/master/.rubocop.yml
# https://rubocop.readthedocs.io/en/latest/configuration/
# https://github.com/rubocop-hq/rubocop/blob/master/manual/cops.md
require:
  - rubocop-rails

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'

Rails:
  Enabled: true

Layout/HashAlignment:
  Enabled: true
  EnforcedLastArgumentHashStyle: always_ignore

Layout/ParameterAlignment:
  EnforcedStyle: with_first_parameter

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EndAlignment:
  EnforcedStyleAlignWith: keyword
  AutoCorrect: true

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Layout/MultilineOperationIndentation:
  EnforcedStyle: aligned

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/CollectionMethods:
  Enabled: true
  PreferredMethods:
      inject: 'inject'

Style/Documentation:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - spec/**/*_spec.rb

Style/GuardClause:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/SignalException:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/ClassLength:
  Max: 100

Metrics/ModuleLength:
  Max: 100

Metrics/BlockLength:
 ExcludedMethods: ['describe', 'context', 'feature', 'scenario', 'let']

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Rails/DynamicFindBy:
  Enabled: false

Rails/TimeZone:
  AutoCorrect: false

Style/SingleLineBlockParams:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/TrivialAccessors:
  AllowPredicates: true
