# Docs: https://github.com/marketplace/actions/rubocop-linter-action

check_name: "RuboCop Results"

versions:
  - rubocop

rubocop_config_path: ".rubocop.yml"

rubocop_fail_level: "warning"

rubocop_force_exclusion: true

bundle: false
