name: CI

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:9.6
        ports: 
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:2.8
        ports: 
          - 6379:6379
        options: --entrypoint redis-server

    steps:
      - uses: actions/checkout@v1
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
          
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: Setup Rails
        run: |
          sudo apt-get -yqq install libpq-dev build-essential git nodejs libpq-dev xvfb libfontconfig wkhtmltopdf libmagickwand-dev
          gem install bundler -v "1.17.3"
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3          

      # - name: Linter
      #   run: |
      #     bundle exec rubocop --force-exclusion

      - name: RuboCop Linter Action
        uses: andrewmcodes/rubocop-linter-action@v3.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tests
        env:
          DATABASE_URL: postgres://postgres:@localhost:5432/test
          REDIS_URL: redis://localhost:6379/0
          RAILS_ENV: test
        run: |
          bundle exec rake db:schema:load
          bundle exec rake db:migrate
          bundle exec rspec